// <auto-generated />
using System;
using Collectify.Model.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Collectify.Model.Data.Migrations
{
    [DbContext(typeof(CollectifyDbContext))]
    partial class CollectifyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Collectify.Model.Collection.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Collectify.Model.Collection.FieldValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DecimalValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("FieldDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ImageValue")
                        .HasColumnType("BLOB");

                    b.Property<int?>("IntValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId");

                    b.HasIndex("ItemId");

                    b.HasIndex("RelatedItemId");

                    b.ToTable("FieldValues");
                });

            modelBuilder.Entity("Collectify.Model.Collection.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreviousItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("PreviousItemId")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Collectify.Model.Entities.FieldDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("FieldDefinitions");
                });

            modelBuilder.Entity("Collectify.Model.Entities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("Collectify.Model.Collection.Collection", b =>
                {
                    b.HasOne("Collectify.Model.Entities.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Collectify.Model.Collection.FieldValue", b =>
                {
                    b.HasOne("Collectify.Model.Entities.FieldDefinition", "FieldDefinition")
                        .WithMany()
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Collectify.Model.Collection.Item", "Item")
                        .WithMany("FieldValues")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collectify.Model.Collection.Item", "RelatedItem")
                        .WithMany()
                        .HasForeignKey("RelatedItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FieldDefinition");

                    b.Navigation("Item");

                    b.Navigation("RelatedItem");
                });

            modelBuilder.Entity("Collectify.Model.Collection.Item", b =>
                {
                    b.HasOne("Collectify.Model.Collection.Collection", "Collection")
                        .WithMany("Items")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collectify.Model.Collection.Item", "PreviousItem")
                        .WithOne("NextItem")
                        .HasForeignKey("Collectify.Model.Collection.Item", "PreviousItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Collection");

                    b.Navigation("PreviousItem");
                });

            modelBuilder.Entity("Collectify.Model.Entities.FieldDefinition", b =>
                {
                    b.HasOne("Collectify.Model.Entities.Template", null)
                        .WithMany("Fields")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectify.Model.Collection.Collection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Collectify.Model.Collection.Item", b =>
                {
                    b.Navigation("FieldValues");

                    b.Navigation("NextItem");
                });

            modelBuilder.Entity("Collectify.Model.Entities.Template", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
